<a href="https://colab.research.google.com/github/MpRonald/Machine-Learning/blob/main/Binary_classifier_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier

In [2]:
data_in_breast = pd.read_csv('https://github.com/MpRonald/datasets/raw/main/entradas_breast.csv')
data_in_breast

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [3]:
data_out_breast = pd.read_csv('https://github.com/MpRonald/datasets/raw/main/saidas_breast.csv')
data_out_breast

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    data_in_breast, data_out_breast, test_size=.2, random_state=42)

In [5]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455, 1), (114, 1))

In [6]:
clf = Sequential()
clf.add(Dense(units=16, activation='relu',
                kernel_initializer='random_uniform',
                    input_dim=30))
clf.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
clf.add(Dense(units=1, activation='sigmoid'))

In [7]:
optim = keras.optimizers.Adamax(lr = 0.001, decay=0.0001)
clf.compile(optimizer=optim, loss='binary_crossentropy', metrics=['binary_accuracy'])

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adamax.py:95: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adamax, self).__init__(name, **kwargs)


In [8]:
clf.fit(X_train, y_train, batch_size=15, epochs=100)

Epoch 1/100
31/31 [==============================] - 2s 3ms/step - loss: 1.0602 - binary_accuracy: 0.5692
Epoch 2/100
31/31 [==============================] - 0s 3ms/step - loss: 0.5813 - binary_accuracy: 0.6308
Epoch 3/100
31/31 [==============================] - 0s 5ms/step - loss: 0.5262 - binary_accuracy: 0.6637
Epoch 4/100
31/31 [==============================] - 0s 3ms/step - loss: 0.5039 - binary_accuracy: 0.6923
Epoch 5/100
31/31 [==============================] - 0s 3ms/step - loss: 0.4827 - binary_accuracy: 0.7253
Epoch 6/100
31/31 [==============================] - 0s 4ms/step - loss: 0.4641 - binary_accuracy: 0.7275
Epoch 7/100
31/31 [==============================] - 0s 5ms/step - loss: 0.4532 - binary_accuracy: 0.7538
Epoch 8/100
31/31 [==============================] - 0s 6ms/step - loss: 0.4364 - binary_accuracy: 0.7934
Epoch 9/100
31/31 [==============================] - 0s 4ms/step - loss: 0.4261 - binary_accuracy: 0.8154
Epoch 10/100
31/31 [==========================

In [9]:
y_pred = clf.predict(X_test)
y_pred = y_pred > 0.5

4/4 [==============================] - 0s 3ms/step


In [10]:
predict_test = accuracy_score(y_test, y_pred)
predict_test

0.9210526315789473

In [11]:
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[37,  6],
       [ 3, 68]])

In [12]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.86      0.89        43
           1       0.92      0.96      0.94        71

    accuracy                           0.92       114
   macro avg       0.92      0.91      0.91       114
weighted avg       0.92      0.92      0.92       114



In [13]:
def create_neural_network():
    clf = Sequential()
    clf.add(Dense(units=16, activation='relu',
                    kernel_initializer='random_uniform',
                        input_dim=30))
    clf.add(Dropout(.25))
    clf.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
    clf.add(Dropout(.15))
    clf.add(Dense(units=1, activation='sigmoid'))
    optim = keras.optimizers.Adamax(lr = 0.001, decay=0.0001)
    clf.compile(optimizer=optim, loss='binary_crossentropy', metrics=['binary_accuracy'])

    return clf

In [14]:
clf_nn = KerasClassifier(build_fn=create_neural_network, epochs=100, batch_size=10)

<ipython-input-14-05d7f4d9f368>:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  clf_nn = KerasClassifier(build_fn=create_neural_network, epochs=100, batch_size=10)


In [15]:
results = cross_val_score(estimator=clf_nn, X=data_in_breast, y=data_out_breast,
                          cv=5, scoring='accuracy')

Epoch 1/100


/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adamax.py:95: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adamax, self).__init__(name, **kwargs)


46/46 [==============================] - 1s 2ms/step - loss: 1.7841 - binary_accuracy: 0.5868
Epoch 2/100
46/46 [==============================] - 0s 3ms/step - loss: 1.1472 - binary_accuracy: 0.6286
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.7780 - binary_accuracy: 0.6396
Epoch 4/100
46/46 [==============================] - 0s 2ms/step - loss: 0.7417 - binary_accuracy: 0.6176
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6706 - binary_accuracy: 0.6571
Epoch 6/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6358 - binary_accuracy: 0.6747
Epoch 7/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5828 - binary_accuracy: 0.7077
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6052 - binary_accuracy: 0.6813
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5753 - binary_accuracy: 0.7275
Epoch 10/100
46/46 [==============================] - 0s 2

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adamax.py:95: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adamax, self).__init__(name, **kwargs)


46/46 [==============================] - 1s 2ms/step - loss: 1.8547 - binary_accuracy: 0.5099
Epoch 2/100
46/46 [==============================] - 0s 2ms/step - loss: 0.9954 - binary_accuracy: 0.5912
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.7411 - binary_accuracy: 0.6110
Epoch 4/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6810 - binary_accuracy: 0.6220
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.7556 - binary_accuracy: 0.6154
Epoch 6/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6524 - binary_accuracy: 0.6000
Epoch 7/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6583 - binary_accuracy: 0.6462
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6077 - binary_accuracy: 0.6769
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5781 - binary_accuracy: 0.6440
Epoch 10/100
46/46 [==============================] - 0s 2

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adamax.py:95: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adamax, self).__init__(name, **kwargs)


46/46 [==============================] - 1s 2ms/step - loss: 1.8402 - binary_accuracy: 0.5538
Epoch 2/100
46/46 [==============================] - 0s 2ms/step - loss: 1.0917 - binary_accuracy: 0.5670
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.9368 - binary_accuracy: 0.5912
Epoch 4/100
46/46 [==============================] - 0s 2ms/step - loss: 0.8202 - binary_accuracy: 0.5714
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6781 - binary_accuracy: 0.6505
Epoch 6/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6874 - binary_accuracy: 0.5780
Epoch 7/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6842 - binary_accuracy: 0.5912
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5663 - binary_accuracy: 0.6374
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6066 - binary_accuracy: 0.6154
Epoch 10/100
46/46 [==============================] - 0s 2

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adamax.py:95: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adamax, self).__init__(name, **kwargs)


46/46 [==============================] - 1s 2ms/step - loss: 1.2817 - binary_accuracy: 0.5692
Epoch 2/100
46/46 [==============================] - 0s 2ms/step - loss: 0.8190 - binary_accuracy: 0.5868
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.7319 - binary_accuracy: 0.6088
Epoch 4/100
46/46 [==============================] - 0s 3ms/step - loss: 0.6081 - binary_accuracy: 0.6286
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6106 - binary_accuracy: 0.6747
Epoch 6/100
46/46 [==============================] - 0s 3ms/step - loss: 0.5510 - binary_accuracy: 0.7187
Epoch 7/100
46/46 [==============================] - 0s 3ms/step - loss: 0.6260 - binary_accuracy: 0.6879
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5188 - binary_accuracy: 0.7297
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5619 - binary_accuracy: 0.7011
Epoch 10/100
46/46 [==============================] - 0s 2

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adamax.py:95: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adamax, self).__init__(name, **kwargs)


46/46 [==============================] - 1s 2ms/step - loss: 2.2119 - binary_accuracy: 0.4846
Epoch 2/100
46/46 [==============================] - 0s 2ms/step - loss: 1.0200 - binary_accuracy: 0.5439
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.9453 - binary_accuracy: 0.5768
Epoch 4/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6756 - binary_accuracy: 0.6294
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6308 - binary_accuracy: 0.6469
Epoch 6/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5821 - binary_accuracy: 0.6754
Epoch 7/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5619 - binary_accuracy: 0.6645
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5676 - binary_accuracy: 0.6579
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.5675 - binary_accuracy: 0.6272
Epoch 10/100
46/46 [==============================] - 0s 2

In [16]:
results

array([0.84210526, 0.88596491, 0.92105263, 0.9122807 , 0.92920354])

In [17]:
new_data = np.array(data_in_breast.iloc[147:148,:])
new_data

array([[1.495e+01, 1.877e+01, 9.784e+01, 6.895e+02, 8.138e-02, 1.167e-01,
        9.050e-02, 3.562e-02, 1.744e-01, 6.493e-02, 4.220e+02, 1.909e+03,
        3.271e+03, 3.943e+01, 5.790e-03, 4.877e-02, 5.303e-02, 1.527e-02,
        3.356e-02, 9.368e-03, 1.625e+01, 2.547e+01, 1.071e+02, 8.097e+02,
        9.970e-02, 2.521e-01, 2.500e-01, 8.405e-02, 2.852e-01, 9.218e-02]])

In [18]:
result_data = np.array(data_out_breast.iloc[147:148,:])
result_data

array([[1]])

In [20]:
clf.predict(new_data)

1/1 [==============================] - 0s 19ms/step


array([[0.69046074]], dtype=float32)

In [24]:
new_data2 = np.array(data_in_breast.iloc[2:3,:])
new_data2

array([[1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+03, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e+01, 2.553e+01, 1.525e+02, 1.709e+03,
        1.444e-01, 4.245e-01, 4.504e-01, 2.430e+02, 3.613e-01, 8.758e-02]])

In [25]:
result_data2 = np.array(data_out_breast.iloc[2:3,:])
result_data2

array([[0]])

In [26]:
clf.predict(new_data2)

1/1 [==============================] - 0s 21ms/step


array([[1.4249418e-06]], dtype=float32)