# Numpy

In [1]:
import numpy as np

In [2]:
# criando uma lista
num_list = [10,12,14,16,18,20]

In [3]:
# convertendo em um array numpy
nums_array = np.array(num_list)

In [4]:
# verificando o tipo
type(nums_array)

numpy.ndarray

In [6]:
# criando array de varias dimensoes
row1 = [10,20,30]
row2 = [11,12,13]
row3 = [50,80,100]

nums_2d = np.array([row1,row2,row3,])
nums_2d.shape

(3, 3)

In [7]:
nums_2d

array([[ 10,  20,  30],
       [ 11,  12,  13],
       [ 50,  80, 100]])

#### Utilizando o método arange()

In [10]:
nums_arr = np.arange(5,21)
print(nums_arr)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
# criando uma lista com saltos de 2 em 2 numeros
nums_arr = np.arange(5,21,2)
print(nums_arr)

[ 5  7  9 11 13 15 17 19]


In [14]:
# criando uma lista de '1s'
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


In [16]:
# criando um array de '1s' de 6 linhas e 4 colunas
ones_array = np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# podemos fazer a mesma coisa com 'zeros'
zero_arr = np.zeros(10)
print(zero_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
# podemos fazer um array de 'zeros' de 3 linhas e 6 colunas
zero_arr = np.zeros((3,6))
print(zero_arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
# utilizando o método eyes()
# é utilizado para criar uma matriz onde temos 1 na diagonal
eyes_arr = np.eye(10)
print(eyes_arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [26]:
# utilizamos o método random().rand() para criar uma lista de
# valores randomicos
r = np.random.rand(10,4)
r

array([[0.60523079, 0.07593887, 0.25040371, 0.88774889],
       [0.13847548, 0.65842165, 0.54522184, 0.55658382],
       [0.30880072, 0.12396542, 0.36677833, 0.66794842],
       [0.30320073, 0.73272601, 0.97990155, 0.85335653],
       [0.87737414, 0.87409917, 0.21505098, 0.89321779],
       [0.15628634, 0.43873947, 0.76123512, 0.59037969],
       [0.00360454, 0.7383948 , 0.79699889, 0.72444981],
       [0.03569358, 0.26155072, 0.11216255, 0.92258741],
       [0.7361478 , 0.43247853, 0.33113512, 0.84210427],
       [0.75215286, 0.08104051, 0.93018429, 0.19565254]])

In [30]:
# utilizamos o método random().randn() para criar uma lista de
# valores randomicos com distribuição normal
r = np.random.randn(5,3)
r

array([[-1.09992758, -0.97899021,  1.790246  ],
       [ 0.21676593, -1.21543943,  0.10690566],
       [ 0.26663312, -0.22676976,  0.86697193],
       [-0.08195754, -0.46200296,  0.02714386],
       [ 0.93628538,  0.27058355, -0.68391323]])

In [32]:
# utilizamos o método random().randint() para criar uma lista de
# valores randomicos inteiros
# aqui estamos gerandi uma lista de 10 a 99 com cinco elementos
# aleatorios
r = np.random.randint(10,100,5)
r

array([17, 90, 67, 14, 12])

In [37]:
# usamos s função reshape() para realocar os elementos em um array
r = np.random.rand(2,10)
r

array([[0.84558125, 0.71672022, 0.67268957, 0.02576289, 0.09528801,
        0.05111338, 0.59557216, 0.49732985, 0.96487101, 0.13456236],
       [0.46677431, 0.57305958, 0.91081863, 0.44785969, 0.26396256,
        0.9126465 , 0.48514287, 0.34148935, 0.87779754, 0.97703889]])

In [39]:
r = r.reshape(10,2)
r

array([[0.84558125, 0.71672022],
       [0.67268957, 0.02576289],
       [0.09528801, 0.05111338],
       [0.59557216, 0.49732985],
       [0.96487101, 0.13456236],
       [0.46677431, 0.57305958],
       [0.91081863, 0.44785969],
       [0.26396256, 0.9126465 ],
       [0.48514287, 0.34148935],
       [0.87779754, 0.97703889]])

In [42]:
# acessando um elemento do array
r = np.random.randint(1,20,10)
print(r)
print(f"Acessando o elemento no indice 3: {r[2]}")

[13  7 17 16 11 15  7  6  9 14]
Acessando o elemento no indice 3: 17


In [43]:
# usamos slice para 'dividir' o array, ou simplemente
# para podermos verificar uma parte a qual queremos
r[2:5]

array([17, 16, 11])

In [45]:
print(f'Verfificando valor do até o quinto elemento: {r[:5]}')
print(f'Verfificando valor do após o quinto elemento: {r[5:]}')

Verfificando valor do até o quinto elemento: [13  7 17 16 11]
Verfificando valor do após o quinto elemento: [15  7  6  9 14]


In [49]:
# podemos realizar slice de arrays 2d
arr1 = [10,12,13]
arr2 = [45,32,16]
arr3 = [45,32,16]

slice_2d = np.array([arr1,arr2,arr3])
print(slice_2d[:2,:]) # duas linas todos os elementos
print(slice_2d[:2,:1]) # duas linhas somente o primeiro elemento

[[10 12 13]
 [45 32 16]]
[[10]
 [45]]


# Expressões Aritméticas

In [55]:
# para realizarmos uma operação de raiz qudrada usamos o sqrt()
n = [100,250,320,410,505]
raiz_n = np.sqrt(n)
raiz_n

array([10.        , 15.8113883 , 17.88854382, 20.24845673, 22.47220505])

In [57]:
# encontrando o log dos numeros
n = [50,60,70,80,90,100]
log_n = np.log(n)
log_n

array([3.91202301, 4.09434456, 4.24849524, 4.38202663, 4.49980967,
       4.60517019])

In [62]:
# utilizamos a função exp() para expoentes
n = [0.1,0.2,0.3]
exp_n = np.exp(n)
exp_n

array([1.10517092, 1.22140276, 1.34985881])

In [65]:
# verificando os seno e cosseno dos numeros
n = [3,4,5,6]
seno_n = np.sin(n)
cos_n = np.cos(n)
print(f"O seno é: {seno_n}\nO cosseno é: {cos_n}")

O seno é: [ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
O cosseno é: [-0.9899925  -0.65364362  0.28366219  0.96017029]


#### Multiplicação entre Matrizes

In [66]:
m1 = [7,16,25,44]
m2 = [19,4,17,2]
m3 = [12,65,10,21]

arr_2d = np.array([m1,m2,m3])
mult = np.multiply(arr_2d,arr_2d)
mult

array([[  49,  256,  625, 1936],
       [ 361,   16,  289,    4],
       [ 144, 4225,  100,  441]])