<a href="https://colab.research.google.com/github/MpRonald/Machine-Learning/blob/main/SVR_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error

In [2]:
house = pd.read_csv('https://raw.githubusercontent.com/MpRonald/datasets/main/house_prices.csv')

In [3]:
X_houses = house.iloc[:,3:19].values
X_houses

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [4]:
y_houses = house.iloc[:,2].values
y_houses

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [5]:
X_house_train, X_house_test, y_house_train, y_house_test = \
train_test_split(X_houses, y_houses, test_size=0.2, random_state=0)

In [6]:
X_house_train.shape, y_house_train.shape

((17290, 16), (17290,))

In [7]:
X_house_test.shape, y_house_test.shape

((4323, 16), (4323,))

In [8]:
std_X = StandardScaler()
std_y = StandardScaler()
X_train_scaled = std_X.fit_transform(X_house_train)
y_train_scaled = std_y.fit_transform(y_house_train.reshape(-1,1))

In [9]:
X_test_scaled = std_X.transform(X_house_test)
y_test_scaled = std_y.transform(y_house_test.reshape(-1,1))

In [10]:
X_train_scaled.shape, y_train_scaled.shape

((17290, 16), (17290, 1))

In [11]:
X_test_scaled.shape, y_test_scaled.shape

((4323, 16), (4323, 1))

In [12]:
reg_srv = SVR(kernel='rbf').fit(X_train_scaled, y_train_scaled)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
reg_srv.score(X_train_scaled, y_train_scaled)

0.8022023251592605

In [14]:
reg_srv.score(X_test_scaled, y_test_scaled)

0.7970270608704864

In [17]:
svr_pred = reg_srv.predict(X_test_scaled)
svr_pred

array([-0.52568937,  3.3788823 ,  0.04597442, ..., -0.37777563,
       -0.72723365, -0.16014809])

In [18]:
y_test_inverse = std_y.inverse_transform(y_test_scaled)

In [20]:
pred_inverse = std_y.inverse_transform(svr_pred.reshape(-1,1))

In [21]:
mean_absolute_error(y_test_inverse, pred_inverse)

78067.00599904536

# END